"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.pointsCalculateParameter2 = exports.pointsCalculateParameter1 = exports.fullScreenWeight = exports.firstLayoutName = exports.userTimingCategory = exports.paintName = exports.paintEventsCategory = void 0;
exports.paintEventsCategory = 'devtools.timeline';
exports.paintName = 'Paint';
exports.userTimingCategory = 'blink.user_timing';
exports.firstLayoutName = 'firstLayout';
exports.fullScreenWeight = 2;
exports.pointsCalculateParameter1 = 2;
exports.pointsCalculateParameter2 = 4;
